"""create audit tables

Governance & Administration - Phase 1 (Audit Log). Creates two tables:

``audit_events``
  * ``id``            UUID primary key, DB-generated by default
  * ``occurred_at``   timezone-aware, server-defaulted to now()
  * ``action``        CHECK-constrained to the action vocabulary
  * ``entity_type``   CHECK-constrained to the entity-type vocabulary
  * ``entity_id`` / ``entity_label``   loose reference + human-name snapshot
                     (no FK - the audited record may later be deleted)
  * ``actor_user_id``  FK -> users.id (SET NULL) - nullable
  * ``actor_email``    actor snapshot; explains "who" after a user is removed
  * ``request_id`` / ``ip_address`` / ``user_agent``   request context
  * ``metadata``       JSONB summary (never a request body / secret)

``audit_changes``
  * ``id``             UUID primary key
  * ``audit_event_id`` FK -> audit_events.id (CASCADE)
  * ``field_name``     non-empty
  * ``old_value`` / ``new_value``  safe serialized text; NULL == a real null

Indexes cover the audit query surface: ``occurred_at`` (default ordering + date
filters), ``actor_user_id``, ``action``, ``entity_type``, ``entity_id`` and the
compound ``(entity_type, entity_id)`` for the "everything about this record"
lookup used by future Trash / entity history. The JSONB ``metadata`` is not
indexed.

``downgrade`` drops both tables (child first) - reversible.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-09-02 10:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b2c3d4e5f6a7"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ACTIONS = (
    "CREATE",
    "UPDATE",
    "STATUS_CHANGED",
    "RELATION_CHANGED",
    "RESOLVED",
    "REOPENED",
    "LOGIN",
    "LOGOUT",
    "DELETE",
    "RESTORE",
    "ROLE_ASSIGNED",
    "ROLE_REMOVED",
    "PERMISSION_CHANGED",
)
_ENTITY_TYPES = (
    "Asset",
    "Incident",
    "Authentication",
    "User",
    "Role",
    "Permission",
)


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    op.create_table(
        "audit_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("entity_label", sa.String(length=300), nullable=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            _in_clause("action", _ACTIONS), name=op.f("ck_audit_events_action_valid")
        ),
        sa.CheckConstraint(
            _in_clause("entity_type", _ENTITY_TYPES),
            name=op.f("ck_audit_events_entity_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"])
    op.create_index("ix_audit_events_actor_user_id", "audit_events", ["actor_user_id"])
    op.create_index("ix_audit_events_action", "audit_events", ["action"])
    op.create_index("ix_audit_events_entity_type", "audit_events", ["entity_type"])
    op.create_index("ix_audit_events_entity_id", "audit_events", ["entity_id"])
    op.create_index(
        "ix_audit_events_entity_type_entity_id",
        "audit_events",
        ["entity_type", "entity_id"],
    )

    op.create_table(
        "audit_changes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("audit_event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "char_length(field_name) > 0",
            name=op.f("ck_audit_changes_field_name_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.id"],
            name=op.f("fk_audit_changes_audit_event_id_audit_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_changes")),
    )
    op.create_index(
        "ix_audit_changes_audit_event_id", "audit_changes", ["audit_event_id"]
    )


def downgrade() -> None:
    op.drop_table("audit_changes")
    op.drop_table("audit_events")
