"""create incidents tables

The Incident Management schema (v0.5). Creates three tables:

``incidents``
  * ``id``           UUID primary key, DB-generated by default
  * ``title``        required, non-empty (CHECK)
  * ``description``  optional free text
  * ``severity`` / ``status`` / ``priority``  required; each constrained by a
                    CHECK to its catalog values. ``status`` server-defaults to
                    ``'Open'``.
  * ``owner``        optional
  * ``started_at``   required, server-defaulted to now() (operator may backdate)
  * ``detected_at`` / ``resolved_at``  optional lifecycle marks
  * ``created_by``   FK -> users.id (RESTRICT); the authenticated author
  * ``created_at`` / ``updated_at``  timezone-aware, server-defaulted to now()

``incident_assets``  (real many-to-many Incident <-> Asset)
  * composite PK ``(incident_id, asset_id)`` - also the uniqueness guarantee
  * both FKs ``ON DELETE CASCADE``
  * secondary index on ``asset_id`` for the "incidents affecting this asset" lookup

``incident_events``  (persisted timeline)
  * ``id``           UUID primary key
  * ``incident_id``  FK -> incidents.id (CASCADE)
  * ``type``         CHECK-constrained to the event vocabulary
  * ``message``      required, non-empty
  * ``created_by``   FK -> users.id (SET NULL) - nullable for future system events
  * ``created_at``   timezone-aware, server-defaulted to now()
  * composite index ``(incident_id, created_at)`` for ordered timeline reads

``downgrade`` drops the three tables (children first) - reversible.

Revision ID: a1b2c3d4e5f6
Revises: 7f3a9c2b1e84
Create Date: 2026-09-01 13:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "7f3a9c2b1e84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SEVERITIES = ("Critical", "High", "Medium", "Low")
_STATUSES = ("Open", "Investigating", "Identified", "Monitoring", "Resolved", "Closed")
_PRIORITIES = ("P1", "P2", "P3", "P4")
_EVENT_TYPES = (
    "CREATED",
    "STATUS_CHANGED",
    "SEVERITY_CHANGED",
    "PRIORITY_CHANGED",
    "OWNER_CHANGED",
    "ASSET_ADDED",
    "ASSET_REMOVED",
    "COMMENT",
    "RESOLVED",
    "REOPENED",
)


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    op.create_table(
        "incidents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'Open'"),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=4), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(title) > 0", name=op.f("ck_incidents_title_not_empty")
        ),
        sa.CheckConstraint(
            _in_clause("severity", _SEVERITIES),
            name=op.f("ck_incidents_severity_valid"),
        ),
        sa.CheckConstraint(
            _in_clause("status", _STATUSES),
            name=op.f("ck_incidents_status_valid"),
        ),
        sa.CheckConstraint(
            _in_clause("priority", _PRIORITIES),
            name=op.f("ck_incidents_priority_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_incidents_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index("ix_incidents_severity", "incidents", ["severity"])
    op.create_index("ix_incidents_status", "incidents", ["status"])
    op.create_index("ix_incidents_priority", "incidents", ["priority"])
    op.create_index("ix_incidents_started_at", "incidents", ["started_at"])
    op.create_index("ix_incidents_updated_at", "incidents", ["updated_at"])
    op.create_index("ix_incidents_created_at", "incidents", ["created_at"])

    op.create_table(
        "incident_assets",
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_assets_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_incident_assets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "incident_id", "asset_id", name=op.f("pk_incident_assets")
        ),
    )
    op.create_index(
        "ix_incident_assets_asset_id", "incident_assets", ["asset_id"]
    )

    op.create_table(
        "incident_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(message) > 0",
            name=op.f("ck_incident_events_message_not_empty"),
        ),
        sa.CheckConstraint(
            _in_clause("type", _EVENT_TYPES),
            name=op.f("ck_incident_events_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_events_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_incident_events_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_events")),
    )
    op.create_index(
        "ix_incident_events_incident_id_created_at",
        "incident_events",
        ["incident_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_table("incident_events")
    op.drop_table("incident_assets")
    op.drop_table("incidents")
