"""create assets table

The first business-domain schema migration for InfraGuard AI (Assets /
Infrastructure Inventory).

Creates ``assets``:
  * ``id``            UUID primary key, DB-generated by default
  * ``name``          required, non-empty (CHECK)
  * ``asset_type`` / ``environment`` / ``criticality`` / ``status``
                     required; each constrained by a CHECK to its catalog values
  * ``hostname`` / ``ip_address`` / ``description`` / ``owner``   optional
  * ``is_active``     boolean, default true (soft-deactivation flag)
  * ``created_at`` / ``updated_at``  timezone-aware, server-defaulted to now()

Indexes cover the list-filter columns plus ``name`` and ``created_at``. No
UNIQUE constraint: assets legitimately repeat (e.g. the same name across
Production and Staging).

``downgrade`` drops the table and everything attached to it - reversible.

Revision ID: 7f3a9c2b1e84
Revises: 02c49f7b5787
Create Date: 2026-09-01 12:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7f3a9c2b1e84"
down_revision: str | None = "02c49f7b5787"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ASSET_TYPES = (
    "Server",
    "Virtual Machine",
    "Database",
    "Application",
    "Network Device",
    "Container",
    "Kubernetes Cluster",
    "Cloud Resource",
)
_ENVIRONMENTS = ("Production", "Staging", "Development", "Test")
_CRITICALITIES = ("Critical", "High", "Medium", "Low")
_STATUSES = ("Operational", "Degraded", "Maintenance", "Offline")


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    op.create_table(
        "assets",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type", sa.String(length=40), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.Column("criticality", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(name) > 0", name=op.f("ck_assets_name_not_empty")),
        sa.CheckConstraint(
            _in_clause("asset_type", _ASSET_TYPES),
            name=op.f("ck_assets_asset_type_valid"),
        ),
        sa.CheckConstraint(
            _in_clause("environment", _ENVIRONMENTS),
            name=op.f("ck_assets_environment_valid"),
        ),
        sa.CheckConstraint(
            _in_clause("criticality", _CRITICALITIES),
            name=op.f("ck_assets_criticality_valid"),
        ),
        sa.CheckConstraint(
            _in_clause("status", _STATUSES),
            name=op.f("ck_assets_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
    )
    op.create_index("ix_assets_name", "assets", ["name"])
    op.create_index("ix_assets_asset_type", "assets", ["asset_type"])
    op.create_index("ix_assets_environment", "assets", ["environment"])
    op.create_index("ix_assets_criticality", "assets", ["criticality"])
    op.create_index("ix_assets_status", "assets", ["status"])
    op.create_index("ix_assets_is_active", "assets", ["is_active"])
    op.create_index("ix_assets_created_at", "assets", ["created_at"])


def downgrade() -> None:
    op.drop_table("assets")
