"""create users table

The first real schema migration for InfraGuard AI (v0.2 - Authentication).

Creates ``users``:
  * ``id``            UUID primary key, DB-generated by default
  * ``email``         unique (uq_users_email; PostgreSQL backs it with an index),
                      forced lowercase and non-empty by CHECK constraints
  * ``password_hash`` non-empty Argon2id hash
  * ``is_active``     boolean, default true
  * ``created_at`` / ``updated_at``  timezone-aware, server-defaulted to now()

``downgrade`` drops the table (and with it every constraint/index) - reversible.

Revision ID: 02c49f7b5787
Revises:
Create Date: 2026-08-31 18:02:43.679248
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "02c49f7b5787"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(email) > 0", name=op.f("ck_users_email_not_empty")),
        sa.CheckConstraint(
            "char_length(password_hash) > 0",
            name=op.f("ck_users_password_hash_not_empty"),
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )


def downgrade() -> None:
    op.drop_table("users")
